export const nameBand = 'MANZ';
export const nameSongs = [
	"LOVE ME BETTER", /*1) (8.0/10)*/
	"AMOR IMPOSIBLE", /*2) (8.0/10)*/
	"SOMOS LA SECTA DE ASTRO", /*3*/
	"EN MI LOCAL FUNCIONABA (ORCHESTRAL)", /*4*/
	"ASYNC KAWAII", /*5*/
	"NO QUIERO CAMBIAR (METAL GHOTIC)", /*6*/
	"AVOCADO DANCE", /*7*/
	"AMOR IMPOSIBLE (METAL)", /*8*/
	"EN LO DE MANZ", /*9*/
	"WE WISH YOU A JAVASCHRISTMAS (PIRATE)", /*10*/
	"PRAISE THE CSS MASTER", /*11*/
	"MANIAC MANSION", /*12*/
	"TRON LEGACY", /*13*/
	"NO QUIERO CAMBIAR", /*14*/
	"WE WISH YOU A JAVASCHRISTMAS (ROCK)", /*15*/
	"YO YA SOY INMORTAL", /*16*/
	"RESOLVI EL PROBLEMA", /*17*/
	"SOY PROGRAMADOR FREELANCE", /*18*/
	"EN MI LOCAL FUNCIONABA", /*19*/
	"HA FUNCIONADO", /*20*/
]